name: Build SukiSU Ultra (Docker Build Environment)

on:
  workflow_dispatch:
    inputs:
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '5.10'
        type: choice
        options:
          - '5.10'
          - '5.15'
      ANDROID_VERSION:
        description: "Android版本"
        required: true
        default: 'android14'
        type: choice
        options:
          - android13
          - android14
      KPM:
        type: boolean
        description: "是否启用KPM模块支持"
        required: true
        default: true
      KERNEL_NAME:
        description: "自定义内核名称后缀"
        required: true
        default: '-SukiSU-Ultra-MT6895'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04
      options: --privileged
    
    env:
      DEBIAN_FRONTEND: noninteractive
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      
    steps:
      - name: Maximize build space
        run: |
          df -h
          rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          df -h
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory '*'

      - name: Install dependencies (Ubuntu 20.04 base)
        run: |
          apt-get update -qq
          apt-get install -y -qq \
            bc bison build-essential ccache curl flex \
            g++-multilib gcc-multilib git gnupg gperf \
            imagemagick lib32ncurses5-dev lib32readline-dev \
            lib32z1-dev liblz4-tool libncurses5 libncurses5-dev \
            libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
            lzop pngcrush rsync schedtool squashfs-tools xsltproc \
            zip zlib1g-dev python3 python3-pip python-is-python3 \
            libarchive-tools libelf-dev libfl-dev wget ca-certificates

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
          export PATH=~/bin:$PATH

      - name: Initialize and sync Android GKI kernel
        run: |
          export PATH=~/bin:$PATH
          mkdir -p kernel_workspace
          cd kernel_workspace
          repo init -u https://android.googlesource.com/kernel/manifest \
            -b common-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }} --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          
      - name: Setup SukiSU Ultra
        run: |
          cd kernel_workspace
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
          cd KernelSU
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10606)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          echo "KernelSU Version: $KSU_VERSION"

      - name: Setup SUSFS patches
        run: |
          cd kernel_workspace
          git clone https://gitlab.com/simonpunk/susfs4ksu.git \
            -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }} --depth=1
          
          cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
          cp -r susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp -r susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          
          cd common
          sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
          sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
          
          patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
          echo "SUSFS patches applied"

      - name: Apply LZ4K compression patches
        run: |
          cd kernel_workspace
          git clone https://github.com/ExmikoN/SukiSU_patch.git --depth=1
          
          cp -r SukiSU_patch/other/lz4k/include/linux/* ./common/include/linux/
          cp -r SukiSU_patch/other/lz4k/lib/* ./common/lib/
          cp -r SukiSU_patch/other/lz4k/crypto/* ./common/crypto/
          
          cd common
          if [ -f ../SukiSU_patch/other/lz4k_patch/${{ github.event.inputs.KERNEL_VERSION }}/lz4kd.patch ]; then
            patch -p1 < ../SukiSU_patch/other/lz4k_patch/${{ github.event.inputs.KERNEL_VERSION }}/lz4kd.patch || true
          fi

      - name: Configure kernel
        run: |
          cd kernel_workspace/common
          
          echo "CONFIG_KSU=y" >> arch/arm64/configs/gki_defconfig
          if [ "${{ github.event.inputs.KPM }}" = "true" ]; then
            echo "CONFIG_KPM=y" >> arch/arm64/configs/gki_defconfig
          fi
          
          cat >> arch/arm64/configs/gki_defconfig << EOF
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          CONFIG_KSU_SUSFS_SUS_SU=n
          CONFIG_KSU_MANUAL_HOOK=y
          CONFIG_CRYPTO_LZ4HC=y
          CONFIG_CRYPTO_LZ4K=y
          CONFIG_CRYPTO_LZ4KD=y
          CONFIG_CRYPTO_842=y
          EOF
          
          git add -A
          git commit -m "Add SukiSU Ultra + SUSFS for MT6895" || true

      - name: Customize kernel version
        run: |
          cd kernel_workspace/common
          sed -i 's/res="\$res\$(cat "\$file")"/res="${{ github.event.inputs.KERNEL_NAME }}"/g' scripts/setlocalversion

      - name: Build kernel
        run: |
          cd kernel_workspace
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh -j$(nproc --all)

      - name: Prepare kernel image
        run: |
          cd kernel_workspace/out/*/dist
          if [ ! -f Image ]; then
            echo "Error: Kernel Image not found!"
            ls -lah
            exit 1
          fi
          echo "Kernel built successfully"

      - name: Create AnyKernel3 package
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git --depth=1 anykernel3
          cd anykernel3
          rm -rf .git .github modules patch ramdisk
          
          cat > anykernel.sh << 'EOF'
          # AnyKernel3 Ramdisk Mod Script
          properties() { '
          kernel.string=SukiSU Ultra GKI 2.0 for OnePlus Ace (MT6895)
          do.devicecheck=1
          do.modules=0
          do.systemless=1
          do.cleanup=1
          do.cleanuponabort=0
          device.name1=PGKM10
          device.name2=pickle
          device.name3=OnePlus Ace
          supported.versions=13-14
          supported.patchlevels=
          '; }
          . tools/ak3-core.sh
          dump_boot
          write_boot
          EOF
          
          cp ../kernel_workspace/out/*/dist/Image ./

      - name: Package ZIP
        run: |
          cd anykernel3
          zip -r9 ../SukiSU-Ultra-MT6895-PGKM10-${{ env.KSUVER }}.zip * -x .git .github

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SukiSU-Ultra-MT6895-PGKM10-KSU${{ env.KSUVER }}
          path: SukiSU-Ultra-MT6895-PGKM10-${{ env.KSUVER }}.zip

      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.KSUVER }}-mt6895
          name: SukiSU Ultra GKI 2.0 - MT6895 (KSU ${{ env.KSUVER }})
          body: |
            ## SukiSU Ultra GKI 2.0 for OnePlus Ace (PGKM10)
            
            **设备**: OnePlus Ace (pickle/PGKM10)  
            **处理器**: MediaTek Dimensity 8100-MAX (MT6895)  
            **内核**: ${{ github.event.inputs.KERNEL_VERSION }}  
            **Android**: ${{ github.event.inputs.ANDROID_VERSION }}  
            **KernelSU**: ${{ env.KSUVER }}  
            **KPM**: ${{ github.event.inputs.KPM }}
            
            使用TWRP/OrangeFox Recovery刷入ZIP包即可。
          files: SukiSU-Ultra-MT6895-PGKM10-${{ env.KSUVER }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
